#!/usr/bin/python
import turtle,time
from turtle import Turtle
 
cursor = Turtle()
cursor.speed(2)
 
cursor.penup()
cursor.setposition(-70,0)
cursor.color('red')
cursor.pendown()
cursor.left(90)
cursor.forward(100)
cursor.right(150)
cursor.forward(115)
cursor.left(120)
cursor.forward(115)
cursor.right(150)
cursor.forward(100)
time.sleep(0.5)
cursor.clear()
 
cursor.penup()
cursor.setposition(-70,0)
cursor.right(180)
cursor.color('blue')
cursor.pendown()
cursor.right(30)
cursor.forward(115)
cursor.right(120)
cursor.forward(115)
cursor.right(180)
cursor.forward(57.5)
cursor.left(60)
cursor.forward(60)
time.sleep(0.5)
cursor.clear()
 
 
cursor.penup()
cursor.setposition(-70,0)
cursor.color('green')
cursor.pendown()
cursor.right(90)
cursor.forward(100)
cursor.right(135)
cursor.forward(140)
cursor.left(135)
cursor.forward(100)
time.sleep(0.5)
cursor.clear()
 
 
cursor.penup()
cursor.setposition(-70,0)
cursor.color('black')
cursor.pendown()
cursor.right(90)
cursor.forward(100)
cursor.backward(50)
cursor.left(90)
cursor.forward(100)
cursor.left(90)
cursor.forward(50)
cursor.backward(100)
time.sleep(0.5)
cursor.clear()
 
cursor.penup()
cursor.right(180)
cursor.setposition(-300,0)
 
cursor.color('red')
cursor.pendown()
cursor.left(90)
cursor.forward(100)
cursor.right(150)
cursor.forward(115)
cursor.left(120)
cursor.forward(115)
cursor.right(150)
cursor.forward(100)
 
cursor.penup()
cursor.left(90)
cursor.forward(50)
cursor.left(90)
 
cursor.color('blue')
cursor.pendown()
cursor.right(30)
cursor.forward(115)
cursor.right(120)
cursor.forward(115)
cursor.right(180)
cursor.forward(57.5)
cursor.left(60)
cursor.forward(60)
cursor.backward(60)
cursor.left(120)
cursor.forward(57.5)
 
cursor.penup()
cursor.left(60)
cursor.forward(50)
cursor.left(90)
 
cursor.color('green')
cursor.pendown()
cursor.forward(100)
cursor.right(135)
cursor.forward(140)
cursor.left(135)
cursor.forward(100)
cursor.backward(100)
 
cursor.penup()
cursor.right(90)
cursor.forward(50)
cursor.left(90)
 
cursor.color('black')
cursor.pendown()
cursor.right(90)
cursor.forward(100)
cursor.backward(50)
cursor.left(90)
cursor.forward(100)
cursor.left(90)
cursor.forward(50)
cursor.backward(100)
cursor.forward(50)
 
cursor.hideturtle()
turtle.done()
